### ISSUE TITLE
Question on sparse layers

### ISSUE THREAD

**Issue by yonderblue** [unixpickle/weakai#1]
For the neuralnet pkg, any chance I could get a hint or very short example about connecting up layers that are sparsely connected?

**Comment by unixpickle** [comment]
I haven't touched the neuralnet package in a long long time. Probably the best bet would be to mask a dense layer with a sparse array of 1's.

**Comment by yonderblue** [comment]
Thanks for the hint, I assume you mean with your Variable type. I'll also look at creating another layer type since that will speed things up whereas the mask I don't believe would.

Also I noticed this repo doesn't show up well in github searches to do with "neural" kind of keywords, yet is perhaps one of the more comprehensive choices in Go, might want to put a few more keywords in the repo description.

Thanks!

**Comment by unixpickle** [comment]
The neuralnet package here is much older than my newer [anynet](https://github.com/unixpickle/anynet) framework. That framework is also in go and supports CUDA and 32-bit floats for better performance.
